/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./index.html",
    "./src/**/*.{vue,js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      fontFamily: {
        sans: ['Inter', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        mono: ['"JetBrains Mono"', 'ui-monospace', 'SFMono-Regular', 'Menlo', 'monospace'],
      },
      boxShadow: {
        glow: '0 0 0 1px rgba(34, 197, 94, 0.15), 0 8px 30px -12px rgba(34, 197, 94, 0.25)',
        card: '0 1px 2px rgba(0, 0, 0, 0.4), 0 8px 24px -16px rgba(0, 0, 0, 0.6)',
      },
      keyframes: {
        'fade-in': {
          '0%': { opacity: '0', transform: 'translateY(4px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
      },
      animation: {
        'fade-in': 'fade-in 0.35s cubic-bezier(0.16, 1, 0.3, 1)',
      },
    },
  },
  plugins: [require("daisyui")],
  daisyui: {
    darkTheme: "dark",
    themes: [
      {
        dark: {
          "primary": "#22c55e",
          "primary-content": "#04200f",
          "secondary": "#a78bfa",
          "secondary-content": "#1a1033",
          "accent": "#22c55e",
          "accent-content": "#04200f",
          "neutral": "#1c1c21",
          "neutral-content": "#d4d4d8",
          "base-100": "#121216",
          "base-200": "#09090b",
          "base-300": "#26262b",
          "base-content": "#e4e4e7",
          "info": "#38bdf8",
          "info-content": "#04181c",
          "success": "#34d399",
          "success-content": "#04231a",
          "warning": "#fbbf24",
          "warning-content": "#241a04",
          "error": "#f87171",
          "error-content": "#2a0a0a",
          "--rounded-box": "0.75rem",
          "--rounded-btn": "0.5rem",
          "--rounded-badge": "0.375rem",
          "--border-btn": "1px",
          "--tab-radius": "0.5rem",
        },
      },
      {
        light: {
          "primary": "#16a34a",
          "primary-content": "#ffffff",
          "secondary": "#7c3aed",
          "secondary-content": "#ffffff",
          "accent": "#16a34a",
          "accent-content": "#ffffff",
          "neutral": "#1c1c21",
          "neutral-content": "#fafafa",
          "base-100": "#ffffff",
          "base-200": "#fafafa",
          "base-300": "#e4e4e7",
          "base-content": "#18181b",
          "info": "#0284c7",
          "info-content": "#ffffff",
          "success": "#059669",
          "success-content": "#ffffff",
          "warning": "#d97706",
          "warning-content": "#ffffff",
          "error": "#dc2626",
          "error-content": "#ffffff",
          "--rounded-box": "0.75rem",
          "--rounded-btn": "0.5rem",
          "--rounded-badge": "0.375rem",
          "--border-btn": "1px",
          "--tab-radius": "0.5rem",
        },
      },
    ],
  },
}
